### PR TITLE
Enable Support for Multi-GPU Training

### PR DESCRIPTION
**Pull request by sorenmacbeth**
* Support Multi-GPU training
* Address some `FutureWarning` and `PerformanceWarning`
* Change type of `precision` to string to match PL
* Allow setting of `pickle_protocol` in `DataConfig` to save very large DataModules
* Preserve original index in `TabularDataset`

I've tested this using the DDP strategy but I believe it will work with other PL strategies as well.

----
📚 Documentation preview 📚: https://pytorch-tabular--517.org.readthedocs.build/en/517/

### CODE REVIEW

**Comment by sorenmacbeth** [comment]
@manujosephv wish i knew a release was coming or i would have push this up sooner, sorry about that

**Comment by sorenmacbeth** [comment]
@manujosephv I see some python 3.8 fails because the option context im using isn't available. let me know how you'd like me to address those

**Comment by sorenmacbeth** [comment]
@manujosephv I removed the commits that tried to address the `FutureWarning` regarding silent downcasting and `fillna` to maintain support back to pandas 2.0.3 and python 3.8.

All checks are passing now

**Review by manujosephv — APPROVED** [review]

**Comment by manujosephv** [comment]
@sorenmacbeth Sorry for the delay. got caught up with some other things last week! Thanks for this PR.. Merging it :)

**Pull request merged**
