### PR TITLE
Fix metrics_prob_inputs naming error

### PR DESCRIPTION
**Pull request by EeyoreLee**
The misnamed metrics_prob_inputs in the code results in no way to use probability calculations in the metrics under the classification task. 

----
:books: Documentation preview :books:: https://pytorch-tabular--239.org.readthedocs.build/en/239/

### CODE REVIEW

**Comment by EeyoreLee** [comment]
Is it possible to merge this PR faster so that my experiment can proceed quickly?

**Comment by EeyoreLee** [comment]
Changing the naming in the loop may cause the metrics_prob_input of a non-custom metric to be unavailable, and it seems more reasonable to override the custom one to metrics_prob_input

**Comment by manujosephv** [comment]
I see the problem and I think its larger than this.. in some places its `metrics_prob_input` and some other places `metrics_prob_inputs`.

I'll merge the PR provided the tests pass. But the right way would be to replace all instances of `metrics_prob_inputs` with `metrics_prob_input` everywhere in the code base. Will have to revise that in another PR sometime later..

**Comment by EeyoreLee** [comment]
I second it. But the param in `fit` function named `metrics_prob_inputs`, if so, some people who used this library before will not be compatible when updating. At the moment this change does not seem to bring some bugs except for some confusion in naming, unless you choose between maintaining two parameters or dropping compatibility. So I didn't change all the `metrics_prob_inputs`, because it depends on your architecture idea. And thanks for your quick reply.

**Comment by manujosephv** [comment]
You are right.. I meant as a future PR, I would deprecate the `metrics_prob_inputs`, and remove it in a future release. Thanks for the PR. I'm merging it

**Pull request merged**
