### PR TITLE
Github workflow for testing and linting.

### PR DESCRIPTION
**Pull request by wsad1**
Added workflows for linting and testing.

- The testing workflow seems to pass. Do check out testing.yml and let me know if there's a better way to set things up.
- The liniting workflow fails.  Are there some flake8 options i need to use to prevent this?

### CODE REVIEW

**Comment by Actis92** [comment]
Hi @wsad1 talking with @manujosephv I have some suggestions: 

1) It's not useful to have 2 pipelines, one for the tests and one for the linting. It's better to use tox (like it was done in travis, and when one develop locally) If you want can make something similar:
`- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: tox`
2) For the problems find with flake8 depends by @manujosephv how he want to manages. Using tox, inside the tox.ini is possible to add a section in order to ignore some rules. Obviously depends which rules he wants to ignore and which one he prefer to fix the code. For example:
`[flake8]
ignore = E501`

**Comment by manujosephv** [comment]
E501 for sure, and I see there are a few corrections to be done for linting.. Will have to take that up after merging @Actis92  PR.  But lets only fail the overall workflow (i.e. the unit test and deployment when some serious errors like syntax errors E9,F63,F7,F82. And also ignore the files in examples folder from linting.

And we should also only build and upload to PyPi for commits with tags. Rest of the commits just have linting and unit test..

**Comment by Actis92** [comment]
For what concern build and upload on PyPI when a tags is pushed, in my repo I have used a different pipeline like this one in case can be helpful for you
`name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@master"
      - name: "Set up Python 3.9"
        uses: "actions/setup-python@v1"
        with:
          python-version: 3.9
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}`

**Comment by manujosephv** [comment]
@wsad1 Were you able to review @Actis92 's comments?

**Comment by wsad1** [comment]
@Actis92 thanks for your comments.
1. The reason I have separate files is so that we could have separate badges for linting and testing. But, if that's not needed I think we can combine the two files.
2. Could you elaborate on the need for tox. As far as I know github actions can achieve most things tox can like testing on different environment, setting environment variables etc.

**Comment by manujosephv** [comment]
@wsad1 Publishing the package to pypi is something that is still missing, am I right?

**Comment by wsad1** [comment]
@manujosephv yes deploying to pypi is still missing. I was planning to add that as a separate PR once we merge this.
But it looks like @Actis92  has a good solution. @Actis92 are you planning to create a PR for the deployment workflow or would you prefer I do it?

**Comment by wsad1** [comment]
Thanks @Actis92 , this is a good point. The configurations in actions might be different. 
We can make sure the flake8 and test configs are same for users and in github actions by using setup.cfg. But the users might still use a different version of python.

**Review by manujosephv — APPROVED** [review]
Looks good.. Approving..

**Comment by manujosephv** [comment]
> 

Merging this PR. In the next PR let's include PyPi push, tox cleanup, and updating documentation.

**Pull request merged**
