### PR TITLE
bump: `pytorch-lightning >=2.0` & enable Torch 2.0+

### PR DESCRIPTION
**Pull request by Borda**
trying to bump the `pytorch-lightning` to 2.0+

re-work of #233, #261 and #271

----
:books: Documentation preview :books:: https://pytorch-tabular--297.org.readthedocs.build/en/297/

### CODE REVIEW

**Comment by Borda** [comment]
seems like all failing on URL error so likely unrelated to the change and restart could help

**Comment by sorenmacbeth** [comment]
would love to see this one merged 🙏

**Comment by manujosephv** [comment]
definitely! Just having a bit of problem with the test suite. UCI ML certificate expired, causing all the test cases to fail..

**Comment by Borda** [comment]
@manujosephv could you please help here...

**Comment by manujosephv** [comment]
Hopefully #303 fixes this issue and unblocks all the other PRs

**Comment by Borda** [comment]
The new `on_validation_epoch_end` does not have output so that part need to be updated...

**Comment by manujosephv** [comment]
ah! I just checked the new api. How about `on_validation_batch_end`? Is that getting called at the end of each batch in validation data?

**Comment by Borda** [comment]
> ah! I just checked the new api. How about `on_validation_batch_end`? Is that getting called at the end of each batch in validation data?

Yes

**Comment by manujosephv** [comment]
then I guess will need to save the outputs at the end of each batch and then use the `on_validation_epoch_end` to do the processing..  I'll try to make the change soon

**Comment by Borda** [comment]
that is strange, so I added you to the forked repo or if you can add me here for next time... :)

**Comment by manujosephv** [comment]
@Borda  Just merged the other PR #318 . And yeah strange. Anyways, I've added you in here for next time

**Pull request closed without merging**
