### PR TITLE
feat: allow saving model without full dataset

### PR DESCRIPTION
**Pull request by Borda**
When you train a model and later you want to use it for simple inference it is very convenient to use this symmetric functions `save_model` and `load_model`. But when trained on a large dataset the artifact is super large even if you won't ever need the train/vali/test datasets... 
So, this PR will allow the drop of the dataset's DataFrames and save DataModule without them.

----
:books: Documentation preview :books:: https://pytorch-tabular--312.org.readthedocs.build/en/312/

### CODE REVIEW

**Comment by Borda** [comment]
seems the dataset is strangely used for init instead of preserving  once estimated attributes
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 10
      8 ls_models = sorted(glob.glob(os.path.join(PATH_LOAD_MODELS, "tabular_*")))
      9 print(f"found {len(ls_models)} models")
---> 10 models = [TabularModel.load_model(model_dir) for model_dir in ls_models]

Cell In[17], line 10, in <listcomp>(.0)
      8 ls_models = sorted(glob.glob(os.path.join(PATH_LOAD_MODELS, "tabular_*")))
      9 print(f"found {len(ls_models)} models")
---> 10 models = [TabularModel.load_model(model_dir) for model_dir in ls_models]

File /opt/conda/lib/python3.10/site-packages/pytorch_tabular/tabular_model.py:363, in TabularModel.load_model(cls, dir, map_location, strict)
    359     # model_callable = getattr(
    360     #     getattr(models, config._module_src), config._model_name
    361     # )
    362     custom_model = False
--> 363 inferred_config = datamodule.update_config(config)
    364 inferred_config = OmegaConf.structured(inferred_config)
    365 model_args = {
    366     "config": config,
    367     "inferred_config": inferred_config,
    368 }

File /opt/conda/lib/python3.10/site-packages/pytorch_tabular/tabular_datamodule.py:127, in TabularDatamodule.update_config(self, config)
    125 embedding_dims = None
    126 if not self.do_leave_one_out_encoder():
--> 127     categorical_cardinality = [
    128         int(self.train[col].fillna("NA").nunique()) + 1 for col in config.categorical_cols
    129     ]
    130     embedding_dims = [(x, min(50, (x + 1) // 2)) for x in categorical_cardinality]
    131     if hasattr(config, "embedding_dims"):

File /opt/conda/lib/python3.10/site-packages/pytorch_tabular/tabular_datamodule.py:128, in <listcomp>(.0)
    125 embedding_dims = None
    126 if not self.do_leave_one_out_encoder():
    127     categorical_cardinality = [
--> 128         int(self.train[col].fillna("NA").nunique()) + 1 for col in config.categorical_cols
    129     ]
    130     embedding_dims = [(x, min(50, (x + 1) // 2)) for x in categorical_cardinality]
    131     if hasattr(config, "embedding_dims"):

**Comment by Borda** [comment]
tested on kaggle dataset and seems to be working

**Comment by manujosephv** [comment]
@Borda in addition to these changes, we need to make a few more to make this work. I'll take this forward, similar to the other PR. Will merge it to a dev branch, work on it, and raise a fresh PR from that branch..

**Comment by Borda** [comment]
> we need to make a few more to make this work. I'll take this forward.

I am now successfully using this on Kaggle =)

**Comment by manujosephv** [comment]
This would work..  but once you save the model without the saved data, and you load it back, you can't use train or val data loaders.. it's an inference only artifact..

While that is okay, I was working on a way to let the user choose how to cache the results. It can stay in memory, or it can be written to disk. So that the load on memory can be offloaded to disk if needed(at the cost of speed)..

While saving the model, we can let the user decide to save an inference only version, which doesnt save any data and will be low memory.

**Pull request merged**
