### PR TITLE
Added deployment workflow.

### LINKED ISSUE #52: Migrate to Github Actions.
pytorch-tabular currently uses travis and tox for CI/CD, the plan is to move this to github-actions.

**Describe the solution you'd like**
The current CI/CD pipeline uses flake8 for linting, and tests the code with pytest on python 3.7, 3.6 and 3.8. After which the package is deployed to pypi.

The migration to actions can be split into two tasks.

- [x] Create and single/separate workflow for testing and linting.
- [ ] Create a workflow for deployment that depend on the linting and testing workflow(s). It's not very straightforward to have one workflow depend on another, so for starts we could have just one workflow with 3 jobs for testing, linting and deployment.

Any feedback on this plan is welcome :).

### PR DESCRIPTION
**Pull request by wsad1**
Closes #52
This PR makes the following changes.

1. Added a workflow called pypi_deploy.yml. it deploys the package to pypi on tagged releases.
2. deleted travis.yml and tox.ini

Note:
@manujosephv, you'll need to make the following changes before merging this

1. currently pypi_deploy deploys to test pypi, to move deployment to pypi remove the `repository_url` argument.
2. Further you'll also need to create a github secret with your pypi API token, and use that as the `password`.

### CODE REVIEW

**Comment by manujosephv** [comment]
@wsad1  Pardon my ignorance... But setting a secret is tied to an environment.. Is there anything else we need to do to tie that environment to the action workflows?

**Comment by wsad1** [comment]
I added the token as a secret to `wsad1/pytroch_tabular` repository, I guess you should be able to see that. Then I used this secret as the `password` for deploying to test pypi. Does that address your question?

**Comment by manujosephv** [comment]
not exactly... I created the pypi secret.. but when you create a secret, github also asks to create an "environment". so I jave done that as well. But just wondering if there is something to be done to let github actions know a particular workflow is supposed to use this environment.

Also: now we are not using twine to upload to pypi, I'm assuming. Can I remove that from the requirements as well?

**Comment by wsad1** [comment]
Ah I see. So a secret can be tied to an environment or a repository, as explained [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets). If its tied to the repository , like I did for this PR, then then the workflow can directly refer to the secret. But if its tied to an environment then you need to mention the environment in the job as explained [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment). 

Now I am not sure which type of secret we should be using here.

**Pull request closed without merging**
