### PR TITLE
Add multi target classification

### PR DESCRIPTION
**Pull request by YonyBresler**
Added the ability for multi-target classification, discussed in #430.

Highlighting some of the changes:

1. Initiated by having targets a list, same as in multi-target regression
2. In inferred-config, added 'output_cardinality' to track the number of classes per target
3. label_encoder is now a list, [i] corresponds to the i'th target
4. Updated unit tests for all models to include a multi-target variation of classification
5. Updated documentation to remove limitation of no multi-target classification support
6. [pre-commit.ci] auto fixes from pre-commit.com hooks

Things that I'm happy to improve:
1. With custom metrics, we now need a set of parameters for each metric and for each target (since the number of classes can vary). I'm not as familiar with OmegaConf, I created a sub_params_list config object with I omegaConf.create() on the fly, but wondering if there's a cleaner way to do this.
2. Bagging predict would require significant changes to allow multi-target classification. It is not clear to me if multi-target regression is currently supported in tabular_model._combine_predictions()? For now bagging only works correctly with single-target classification.
3. While there are tests to see that multi-target is working, all current model tests only evaluate that it runs without errors, but not that it runs correctly.

----
📚 Documentation preview 📚: https://pytorch-tabular--441.org.readthedocs.build/en/441/

### CODE REVIEW

**Comment by manujosephv** [comment]
Thanks a lot for this PR. This is something that was requested by a lot of folks in the community! I'm running a bit from pillar to post at the moment, but I'll take a look at the code as soon as I get a chance :)

**Comment by manujosephv** [comment]
Thank you @YonyBresler for the excellent PR. I have almost no suggestions except one minor thing about an error message! And apologize for the tardiness in reviewing the PR. Things been crazy at work.

Also, the custom_metrics solution is something I can live with. 

One more thing I would add is a tutorial notebook..  Maybe a How-To guide? That would be a good start to put down how one would use multi-label classification

**Comment by manujosephv** [comment]
Also, maybe we can also add an error message if Multi-label classification or even multi-label regression is used with MDN head

**Comment by manujosephv** [comment]
@YonyBresler Did you manage to take a look at the comment? Or do you want me to make the changes and merge the PR? Let me know. This is a very useful and asked for feature

**Comment by YonyBresler** [comment]
Hi @manujosephv, it's in progress, preparing the notebook I found and fixed a bug with how the metric is reported in some circumstances (already committed) 

There's still an issue with certain metrics (that require probabilities) and auto-lr for model like Gandalf, it causes an error, I believe things are not getting initialized properly with the new changes.

Let me see if I can resolve it, or if not perhaps add a limit to not use auto-lr in multi-target classifier with models that can't handle it right now, but I hope I can fix it.

**Comment by YonyBresler** [comment]
Thanks for your patience @manujosephv, I've resolved the issue (it wasn't a bug, but rather improper configuration) and added a tutorial notebook to walk through multi-target classification (albeit with a very rudimentary 2nd target).

As far as I can tell, should be good to go, please take a look when you get a chance and let me know if there's any issue or ready to merge.

Thanks!

**Comment by manujosephv** [comment]
There is some error in test cases. I think it's not your code, but some library compatibility. I'll try and figure it out as soon as I get some time.

**Comment by YonyBresler** [comment]
It's weird, I tested on a clean python 3.10.14 install and all tests pass, no library issue, so not sure what's causing it on your test script.
Let me know if there's something I can do to help resolve this.

**Comment by YonyBresler** [comment]
Thanks for resolving this issue @Borda!

**Review by manujosephv — APPROVED** [review]

**Pull request merged**
