### PR TITLE
fix in inferred config of output_dim when `target` is an empty list in SSL model

### PR DESCRIPTION
**Pull request by sorenmacbeth**
fix an assumption that `self.target` always has at least 1 item in it's list. SSL models have and empty list.

----
:books: Documentation preview :books:: https://pytorch-tabular--333.org.readthedocs.build/en/333/

### CODE REVIEW

**Comment by manujosephv** [comment]
@sorenmacbeth Thanks for taking up the triage and the PR. Have just a comment in the changes. But it's also failing on a few test cases:
`AttributeError: 'TabularDatamodule' object has no attribute '_output_dim_reg'`
Can you take a look? My day job is keeping me busy these days.. hehe

**Comment by sorenmacbeth** [comment]
@manujosephv changed it up a bit and now it's passing all the tests. lmk my changes look ok

**Comment by manujosephv** [comment]
just one more small thing. Does the below make sense?:
```python
        if config.task == "regression":
            output_dim = self._output_dim_reg
        elif config.task == "classification":
            output_dim = self._output_dim_clf
        elif config.task == "ssl":
            output_dim = None
        else:
            raise ValueError(f"{config.task} is an unsupported task.")
```

**Comment by sorenmacbeth** [comment]
@manujosephv I added your change to the PR as well.

**Review by manujosephv — APPROVED** [review]

**Comment by manujosephv** [comment]
Merged! Thanks for your contribution @sorenmacbeth

**Pull request merged**
