### PR TITLE
Add Built-in Support for Model Stacking

### PR DESCRIPTION
**Pull request by taimo3810**
ISSUE
https://github.com/manujosephv/pytorch_tabular/issues/519

TODO

- [x] Implement model, backbone and config class for stacking
- [x] write tests
- [x] minor refactoring
- [x] check if all tests are passed (local)
- [x] write documentation
- [ ] fix pytest error on python 3.8

----
📚 Documentation preview 📚: https://pytorch-tabular--520.org.readthedocs.build/en/520/

### CODE REVIEW

**Comment by taimo3810** [comment]
@manujosephv
I fixed the error caused by pytest on Python 3.8. Could you please rerun pytest?

**Comment by taimo3810** [comment]
@manujosephv
I fixed some parts of the code again. Sorry, could you please rerun pytest?

**Comment by taimo3810** [comment]
@manujosephv
Sorry, could you rerun pytest?

**Comment by manujosephv** [comment]
@taimo3810 Would you be able to run pytest locally before pushing? might be easier and quicker. I've approved the run this time,

**Comment by taimo3810** [comment]
@manujosephv 
Thank you for pointing that out. You're right—I should have run pytest locally before pushing. 
I’m sorry for the inconvenience caused. I’ll make sure to thoroughly check everything locally next. 
I really appreciate you approving the run this time!

**Review by manujosephv — APPROVED** [review]

**Comment by manujosephv** [comment]
Thanks for this great PR @taimo3810 . I love that you also added documentation and tutorials 😄 . Merging it!

**Pull request merged**
